### Create a User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
 "email": "test2@test2.com", 
 "password": "1234"
}

### Get a user by email.
GET http://localhost:3000/auth?email=test2@test2.com

### Update a user by Id.
PATCH  http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "cat@coolcat.com",
  "password": "456"
}

### Delete a user by Id.
DELETE http://localhost:3000/auth/3